name: joao_foxbit_test
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_clean_architecture: ^4.1.1
  rxdart: ^0.25.0
  websok: ^2.1.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: 1.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.otf
          weight: 400
        - asset: assets/fonts/Gilroy-ExtraBold.otf
          weight: 700